- menu_name: "Kleingedrucktes"

- name: "Kontakt"
  url: "/kontakt/"
  title: "Kontakt"

- name: "Vertragsbedingungen"
  url: "/vertragsbedingungen/"
  title: "Vertragsbedingungen"

- name: "Sitemap"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"

- name: "Impressum"
  url: "/impressum/"
  title: "Impressum"
