- menu_name: "Kleingedrucktes"

- name: "Kontakt"
  url: "/kontakt/"
  title: "Kontakt"

- name: "Vertragsbedingungen"
  url: "/vertragsbedingungen/"
  title: "Vertragsbedingungen"

- name: "Wichtige Informationen"
  url: "/wichtige-informationen/"
  title: "Wichtige Informationen"

- name: "Datenschutz"
  url: "/datenschutz/"
  title: "Informationen zum Datenschutz"

- name: "Sitemap"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"

- name: "Impressum"
  url: "/impressum/"
  title: "Impressum"
